version: '3'
services:
  mongodb:
    container_name: mongo_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongodb_data_container:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=gorafiaidb
    networks:
      - asmd_net

  api:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/gorafiaidb?authSource=admin
      OPENAI_API_KEY: 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
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongodb
    networks:
      - asmd_net

  angular:
    container_name: GorafiAI_Website_container
    build:
      context: ./GorafiAI
      dockerfile: Dockerfile
    environment:
      API_URL: http://api:3000
    restart: always
    ports:
      - 4200:4200
    depends_on:
      - api
    networks:
      - asmd_net

networks:
  asmd_net:
    driver: bridge
